### ISSUE TITLE
RSS Feed Issue

### ISSUE THREAD

**Issue by Jeymen** [wdhdev/free-for-life#49]
Hi @VaibhavSys! There seems to be an issue with the RSS feed you've added recently. I've attached a screenshot of the step it fails. If you can't view the screenshot, here's the error:

```
Run git config --local user.email "actions@github.com"
[main d113cd1] chore: update rss feed
 1 file changed, 2 insertions(+), 2 deletions(-)
To https://github.com/wdhdev/free-for-life
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/wdhdev/free-for-life'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.

```

![image](https://github.com/wdhdev/free-for-life/assets/109573368/6522d018-54ed-4f7f-9fa0-10b618c9b4e3)

**Comment by wdhdev** [comment]
I know why, it is because the other GitHub Action which updates the README commits before the RSS feed. I will fix this.

**Comment by wdhdev** [comment]
Yep, exactly what I expected. I simply resolved it by making the CI run `git pull` before commiting the changes.
