### ISSUE TITLE
Add is-not.tech to the "free subdomains list"

### ISSUE THREAD

**Issue by TrivCodez** [wdhdev/free-for-life#66]

**Comment by wdhdev** [comment]
I cannot reach https://is-not.tech

**Comment by TrivCodez** [comment]
Alright i'll contact the devs

**Comment by TrivCodez** [comment]
Seems like it works for me...

**Comment by wdhdev** [comment]
Must've been my browser, it is now working. You can open a PR by following the [contributing guidelines](../tree/main/CONTRIBUTING.md).
