### ISSUE TITLE
WoSign SSL

### ISSUE THREAD

**Issue by awsjulian** [wdhdev/free-for-life#81]
https://github.com/wdhdev/free-for-life/blob/48a71afc3a7db9a532beb61a1f5a01437827ee72/data/SSL.md?plain=1#L9

I think WoSign should be removed?

- https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html
- https://wiki.mozilla.org/CA/WoSign_Issues

**Comment by wdhdev** [comment]
Yeah, that seems good enough evidence for its removal. If you could open a PR for this, that would be amazing.
