### ISSUE TITLE
Remove bunny dns or ...

### ISSUE THREAD

**Issue by GlitchingPhantom** [wdhdev/free-for-life#93]
The repository is called 'free-for-life,' but Bunny DNS only provides 20 million free queries. Therefore, if a website gets a lot of visitors, those free queries may run out before the owner dies.

**Comment by wdhdev** [comment]
It is still a free plan.

**Comment by BugEncoder** [comment]
But the repo name is 'free-for-life,' even though the plan might not last until the owner dies. So you need to either remove bunny dns from this list or rename the website and repo name
@wdhdev

**Comment by wdhdev** [comment]
"Free For Life" is mainly just a catchy name, not a guarantee. I operate a subdomain service with over 7,000 subdomains and it receives ~28.5 million queries per month, compared to my personal website domain which only receives ~2k queries a month. It is extremely unlikely a regular personal domain name will ever reach that amount, especially with public DNS resolvers like 1.1.1.1 caching DNS records.
