### ISSUE TITLE
Add formbricks

### ISSUE THREAD

**Issue by alvinsjoy** [wdhdev/free-for-life#98]
[Formbricks](https://formbricks.com/) is an Open Source Qualtrics Alternative (can be given inside the forms category)
It has a [free plan](https://formbricks.com/pricing)
![image](https://github.com/user-attachments/assets/5127f1ed-2506-4097-861e-6ab0e554c9a1)
[GitHub Repo](https://github.com/formbricks/formbricks)

**Comment by alvinsjoy** [comment]
https://github.com/wdhdev/free-for-life/blob/7b5f655e25075b853104caabebc7ffbd1c3ae4eb/data/Forms.md?plain=1#L6
Form-data provides a total of 2020 free submissions per month btw
![image](https://github.com/user-attachments/assets/0dc999f6-2c8c-4029-be22-6d21b348853c)

**Comment by wdhdev** [comment]
Seems good to me, feel free to open a PR to add it.

**Comment by alvinsjoy** [comment]
@wdhdev It seems like both form-data and formpost has been mixed up
https://github.com/wdhdev/free-for-life/blob/9c98a65847e91c5e2931c012c483b3121777ef4b/data/Forms.md?plain=1#L6
https://github.com/wdhdev/free-for-life/blob/9c98a65847e91c5e2931c012c483b3121777ef4b/data/Forms.md?plain=1#L15

**Comment by wdhdev** [comment]
Thanks, do you think you can fix that sorting in your PR as well?
